import 'dotenv/config';import express from 'express';import cookieParser from './simple-cookie.js';import bcrypt from 'bcryptjs';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {createClient,findClientByClientId,findClientByContact,findClientById,publicClient,updateClient,createSession,getSession,deleteSession,savePayment} from './db.js';import {startMarketStream,getMarket,addSseClient} from './market.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),backendDir=path.resolve(__dirname,'..'),rootDir=path.resolve(backendDir,'..'),frontendDir=path.join(rootDir,'frontend'),uploadsDir=path.join(backendDir,'uploads');fs.mkdirSync(uploadsDir,{recursive:true});
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'15mb'}));app.use(cookieParser());
const normalizeMobile=v=>String(v||'').replace(/\D/g,''),validPassword=p=>typeof p==='string'&&p.length>=8&&/[A-Z]/.test(p)&&/[0-9]/.test(p)&&/[@#₹]/.test(p);function setSession(res,t,e){res.cookie('alphaedge_session',t,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',expires:new Date(e),path:'/'})}function auth(req,res,next){const s=getSession(req.cookies.alphaedge_session);if(!s)return res.status(401).json({message:'Authentication required.'});req.session=s;req.client=findClientById(s.client_db_id);next()}
app.get('/api/health',(_q,r)=>r.json({ok:true,service:'AlphaEdge Backend',time:new Date().toISOString()}));
app.post('/api/auth/register',async(req,res)=>{const name=String(req.body?.name||'').trim(),mobile=normalizeMobile(req.body?.mobile),email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!name||!/^\d{10}$/.test(mobile)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!validPassword(password))return res.status(400).json({message:'Invalid registration details.'});if(findClientByContact(email)||findClientByContact(mobile))return res.status(409).json({message:'An account with this mobile number or email already exists.'});try{const c=createClient({name,mobile,email,passwordHash:await bcrypt.hash(password,12)});res.status(201).json({client:publicClient(c)})}catch{res.status(500).json({message:'Registration failed.'})}});
app.post('/api/auth/login',async(req,res)=>{const id=String(req.body?.clientId||'').trim().toUpperCase(),password=String(req.body?.password||''),c=findClientByClientId(id);if(!c||!(await bcrypt.compare(password,c.password_hash)))return res.status(401).json({message:'Invalid Client ID or password.'});const s=createSession(c.id,Number(process.env.SESSION_DAYS||7));setSession(res,s.token,s.expires);res.json({client:publicClient(c)})});
app.post('/api/auth/logout',(req,res)=>{deleteSession(req.cookies.alphaedge_session);res.clearCookie('alphaedge_session',{path:'/'});res.json({ok:true})});
app.post('/api/auth/forgot-client',(req,res)=>{const c=findClientByContact(req.body?.contact);if(!c)return res.status(404).json({message:'No account found with that mobile number or email.'});res.json({clientId:c.client_id})});
app.post('/api/auth/forgot-password',async(req,res)=>{const id=String(req.body?.clientId||'').trim().toUpperCase(),contact=req.body?.contact,p=String(req.body?.password||''),c=findClientByClientId(id),byContact=findClientByContact(contact);if(!c||!byContact||byContact.id!==c.id)return res.status(400).json({message:'Client ID and registered mobile/email do not match.'});if(!validPassword(p))return res.status(400).json({message:'Password must be minimum 8 characters and contain 1 uppercase, 1 number and 1 special character (@/#/₹).'});updateClient(c.id,{name:c.name,mobile:c.mobile,email:c.email,passwordHash:await bcrypt.hash(p,12)});res.json({ok:true})});
app.get('/api/auth/me',auth,(req,res)=>res.json({client:publicClient(req.client)}));
app.put('/api/auth/profile',auth,async(req,res)=>{const name=String(req.body?.name||'').trim(),mobile=normalizeMobile(req.body?.phone),email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!name||!/^[0-9]{10}$/.test(mobile)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({message:'Invalid profile details.'});const existing=findClientByContact(email);if(existing&&existing.id!==req.client.id)return res.status(409).json({message:'Email or mobile already belongs to another account.'});if(password&&!validPassword(password))return res.status(400).json({message:'Invalid password format.'});const c=updateClient(req.client.id,{name,mobile,email,passwordHash:password?await bcrypt.hash(password,12):undefined});res.json({client:c})});
app.post('/api/payments/confirm',auth,(req,res)=>{const{course,utr,slipName,slipData}=req.body||{};if(!course||!utr||!slipName||!String(slipData||'').startsWith('data:'))return res.status(400).json({message:'Payment details are incomplete.'});const m=String(slipData).match(/^data:([^;]+);base64,(.+)$/);if(!m)return res.status(400).json({message:'Invalid payment slip.'});const mime=m[1];if(!['image/jpeg','image/png','application/pdf'].includes(mime))return res.status(400).json({message:'Only JPG, PNG or PDF payment slips are allowed.'});const ext=mime==='application/pdf'?'.pdf':mime==='image/png'?'.png':'.jpg',filename=`${Date.now()}-${crypto.randomBytes(6).toString('hex')}${ext}`,out=path.join(uploadsDir,filename);fs.writeFileSync(out,Buffer.from(m[2],'base64'));savePayment({clientDbId:req.client.id,course:String(course),utr:String(utr),slipName:String(slipName),slipPath:path.relative(backendDir,out)});res.status(201).json({ok:true,utr:String(utr)})});
app.get('/api/market',(_q,r)=>r.json(getMarket()));app.get('/api/market-stream',(req,res)=>{res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});const remove=addSseClient(res),ping=setInterval(()=>{try{res.write(': ping\n\n')}catch{}},15000);req.on('close',()=>{clearInterval(ping);remove()})});
if(fs.existsSync(frontendDir)){app.use(express.static(frontendDir));app.get('/{*splat}',(_q,r)=>r.sendFile(path.join(frontendDir,'index.html')))}
const port=Number(process.env.PORT||3000);app.listen(port,()=>console.log(`AlphaEdge backend running on http://localhost:${port}`));startMarketStream();
